export enum ErrorCodes {
  VALIDATION = 'VALIDATION_ERROR',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  NOT_FOUND = 'NOT_FOUND',
  NOT_ALLOWED = 'NOT_ALLOWED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TWO_FA = 'TWO_FA',
  CUSTOM = 'CUSTOM_ERROR',
  INTERNAL = 'INTERNAL_SERVER_ERROR',
}
