export enum ErrorCodes {
  VALIDATION = 'VALIDATION_ERROR',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  NOT_FOUND = 'NOT_FOUND',
  NOT_ALLOWED = 'NOT_ALLOWED',
  CUSTOM = 'CUSTOM_ERROR',
  INTERNAL = 'INTERNAL_SERVER_ERROR',
}
